# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '3.8'

services:
  mysql:
    image: docker.io/bitnami/mysql:8.4
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
